sudo: required
language: generic

services: 
  - docker

before-install: 
  - docker build -t jm5093/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jm5093/multi-docker npm test

after_success:
  - docker build -t jm5093/multi-client ./client
  - docker build -t jm5093/multi-server ./server
  - docker build -t jm5093/multi-nginx ./nginx 
  - docker build -t jm5093/multi-worker ./worker
  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push to docker hub
  - docker push jm5093/multi-client
  - docker push jm5093/multi-server
  - docker push jm5093/multi-nginx
  - docker push jm5093/multi-worker
